// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu_b-4LX4LWYWhz1fFV3uldLRoOurcEso',
    appId: '1:266028894231:web:57bd9af9ce5c326afd7452',
    messagingSenderId: '266028894231',
    projectId: 'chicocache-97480',
    authDomain: 'chicocache-97480.firebaseapp.com',
    storageBucket: 'chicocache-97480.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBcb6GF4iJxHG47znIvirLVPzFwIEk1Y',
    appId: '1:266028894231:android:b9b10f0dddf071e1fd7452',
    messagingSenderId: '266028894231',
    projectId: 'chicocache-97480',
    storageBucket: 'chicocache-97480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6f0Kya7hRzcV5s7ElvadN-A992Fiiwdc',
    appId: '1:266028894231:ios:25f4a5f836c42c37fd7452',
    messagingSenderId: '266028894231',
    projectId: 'chicocache-97480',
    storageBucket: 'chicocache-97480.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6f0Kya7hRzcV5s7ElvadN-A992Fiiwdc',
    appId: '1:266028894231:ios:25f4a5f836c42c37fd7452',
    messagingSenderId: '266028894231',
    projectId: 'chicocache-97480',
    storageBucket: 'chicocache-97480.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu_b-4LX4LWYWhz1fFV3uldLRoOurcEso',
    appId: '1:266028894231:web:4d10e7d9e9159b5cfd7452',
    messagingSenderId: '266028894231',
    projectId: 'chicocache-97480',
    authDomain: 'chicocache-97480.firebaseapp.com',
    storageBucket: 'chicocache-97480.firebasestorage.app',
  );
}
